# Generated by Django 3.0.4 on 2020-06-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address',
            new_name='biography',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='city',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='country',
            new_name='facebook',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_detail',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skype',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
