# Generated by Django 3.0.4 on 2020-05-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20200501_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='price_rent',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price_sell',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to='images/'),
        ),
    ]
