# Generated by Django 3.0.4 on 2020-05-09 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='propperty',
            new_name='property',
        ),
    ]
