# Generated by Django 3.0.4 on 2020-05-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20200509_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
