# Generated by Django 3.0.4 on 2020-06-14 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_property_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='adress',
            new_name='address',
        ),
    ]
