# Generated by Django 3.0.4 on 2020-06-16 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0014_auto_20200614_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='rate',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='room',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(blank=True, choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
