# Generated by Django 3.0.4 on 2020-06-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20200616_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='amount',
        ),
    ]
