# Generated by Django 3.0.4 on 2020-06-18 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_remove_property_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='baby_room',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='square_metre',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
